import Exception from '../../Exception.js';
export default function purgeEventFactory(model) {
    return async function purgeEventAction(_req, res, ctx) {
        if (res.body || (res.code && res.code !== 200)) {
            return;
        }
        const engine = ctx.plugin('database');
        if (!engine)
            return;
        try {
            await engine.truncate(model.snake);
        }
        catch (e) {
            const exception = Exception.upgrade(e);
            res.setError(exception.toJSON());
            return;
        }
        res.fromStatusResponse({
            code: 200,
            status: 'OK',
            results: model.snake
        });
    };
}
;
